### ISSUE TITLE
Not quite working with Babel 7

### ISSUE THREAD

**Issue by calrsom** [Cap32/babel-plugin-shebang#1]
Thanks for the useful plugin!

The plugin seems to output `#!#!/usr/bin/env node` with Babel 7.  I was able to work around this with
```
        plugins: [
            ['shebang', { replacement: '/usr/bin/env node' }]
        ]
```
in the `babel.config.js`.

**Comment by Cap32** [comment]
Fixed by 612e964fe42c33df89d4d8e89ad221c664a7e1a7

Please install the latest version (v1.0.0) from npm.

Thanks for reporting 👍🏿
